name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# Set the access for individual scopes, or use permissions: write-all
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: read
  checks: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode package --file pom.xml -DskipTests
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          fail_on_failure: true
